### PR TITLE
Add phosh to portal's UseIn list

### PR DESCRIPTION
**Pull request by agx**
The compositor is phoc but XDG_CURRENT_DESKTOP has "Phosh".

### CODE REVIEW

**Comment by columbarius** [comment]
> has "Phosh"

Your path has that lower case. Can you please confirm which is the right one?

**Comment by agx** [comment]
@columbarius the `UseIn` comparison in xdg-desktop-portal is case insensitive and GNOME uses lowercase `gnome` everywhere so I used all lowercase as well. The actual `XDG_CURRENT_DESKTOP` is `Phosh`.

**Comment by columbarius** [comment]
All right thanks for the info. Then LGTM

**Comment by columbarius** [comment]
thanks

**Pull request merged**
