### PR TITLE
Remove build error workarounds after pipewire upstream fixes

### PR DESCRIPTION
**Pull request by danshick**

### CODE REVIEW

**Comment by emersion** [comment]
Can you rebase against the current master? 9626411 has already been merged.

Assuming `upstream` is the remote name:

```
git fetch upstream
git rebase upstream/master
```

**Comment by danshick** [comment]
Yeah, whoops.

**Comment by danshick** [comment]
CI is gonna fail because this will only build against pipewire master at the moment. Can CI do an AUR package like pipewire-git?

**Comment by emersion** [comment]
Maybe we should wait for the next pipewire release? This would make it easier for (early) users as well.

**Comment by danshick** [comment]
Makes sense. I'll just leave this PR open then? Can you manually re-run the CI pipeline when the package is updated?

**Comment by emersion** [comment]
Yeah, I'll restart the CI job once we have a new pipewire release.

**Comment by danshick** [comment]
The pipewire package is updated to 0.3.2 in Arch. This PR should pass CI now. @emersion can you re-run it?

**Comment by emersion** [comment]
Done!

**Comment by danshick** [comment]
Thanks, all set.

**Pull request merged**
